---
# vars file for mysql
mysql_repo_pkg_url: "https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm"
mysql_root_password: "RoboShop@1"

# Removed variables related to remote schema download
# schema_zip_url: "https://github.com/rshaik4devops/mysql/archive/main.zip"
schema_workdir: "/tmp" # Keeping this for temporary files
schema_file: "shipping.sql"

# Define local path for schema file
local_schema_src: "../../1-roboshop-source-code-for-1-VM/9-mysql/shipping.sql"